name: Build for ohos

on:
  workflow_dispatch:

env:
  RUST_TOOLCHAIN: nightly-2025-02-15

jobs:
  build: 
    runs-on: ubuntu-latest
    container: ghcr.io/niuhuan/harmony-next-flutter-pipeline-docker/image:3.7.12-ohos-1.0.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: checkout core
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: 'niuhuan/jasmine-rs-core'
          path: 'native'
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: build-core
        run: |
          apt update
          apt install -y build-essential rsync
          rustup target add aarch64-unknown-linux-ohos
          cargo install ohrs
          export OHOS_NDK_HOME=$OHOS_BASE_SDK_HOME
          cd native/jmbackend/platforms/ohos
          make
          find dist -type f -name "*.so" ! -name "librust" -exec rm -f {} \;
      - name: rsync
        run: |
          rsync -av --exclude oh-package.json5 native/jmbackend/platforms/ohos/dist/ ohos/entry/libs/
          rm -rf native
      - name: build hap
        run: |
          sed -i 's/  modal_bottom_sheet: \^3.0.0-pre/  modal_bottom_sheet:\n    git:\n      url: https:\/\/github.com\/niuhuan\/modal_bottom_sheet.git\n      ref: ohos\n      path: modal_bottom_sheet/g' pubspec.yaml
          cp scripts/ohos.images.bak lib/screens/components/images.dart
          cp ci/version.code.txt lib/assets/version.txt
          flutter build hap --target-platform=ohos-arm64
          cd ohos
          hvigorw assembleHap --release
      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: entry-default-unsigned.hap
          path: ohos/entry/build/default/outputs/default/entry-default-unsigned.hap

